### PR TITLE
Resource path fixed for TweakError.swift

### PR DESCRIPTION
**Pull request by saniazafar**
## Description
This PR fixes the following issue which caused after merging #64 
```
JustTweak (10.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | [iOS] xcodebuild:  note: Planning
    - NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [iOS] xcodebuild:  /Users/sania.zafar/Documents/GitHub/JustTweak/JustTweak/Assets/en.lproj/Localizable.strings:1:1: note: detected encoding of input file as Unicode (UTF-8) (in target 'JustTweak-JustTweak' from project 'Pods')
    - ERROR | xcodebuild:  /Users/sania.zafar/Documents/GitHub/JustTweak/JustTweak/Classes/TweakProviders/EphemeralTweakProvider.swift:27:61: error: cannot find 'TweakError' in scope
    - ERROR | xcodebuild:  /Users/sania.zafar/Documents/GitHub/JustTweak/JustTweak/Classes/TweakProviders/EphemeralTweakProvider.swift:35:51: error: cannot find 'TweakError' in scope
    - ERROR | xcodebuild:  /Users/sania.zafar/Documents/GitHub/JustTweak/JustTweak/Classes/TweakProviders/LocalTweakProvider.swift:64:78: error: cannot find 'TweakError' in scope
    - ERROR | xcodebuild:  /Users/sania.zafar/Documents/GitHub/JustTweak/JustTweak/Classes/TweakProviders/LocalTweakProvider.swift:81:23: error: cannot find 'TweakError' in scope
    - ERROR | xcodebuild:  /Users/sania.zafar/Documents/GitHub/JustTweak/JustTweak/Classes/TweakManager.swift:110:23: error: cannot find 'TweakError' in scope
    - ERROR | xcodebuild:  /Users/sania.zafar/Documents/GitHub/JustTweak/JustTweak/Classes/TweakProviders/UserDefaultsTweakProvider.swift:32:78: error: cannot find 'TweakError' in scope
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

[!] JustTweak did not pass validation, due to 7 errors.
You can use the `--no-clean` option to inspect any issue.
```

## Motivation and Context
N/A

## How Has This Been Tested?
N/A

## Screenshots (if appropriate):
N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dchakarov — COMMENTED** [review]
Are you sure `_TweakAccessorGenerator` should be included in the PR?

**Comment by saniazafar** [comment]
> Are you sure `_TweakAccessorGenerator` should be included in the PR?

Not really sure if changing file reference has any impact on this binary. It was generated automatically. I tested the example app which works fine. Do you think I should remove it?

**Comment by dchakarov** [comment]
> > Are you sure `_TweakAccessorGenerator` should be included in the PR?
> 
> Not really sure if changing file reference has any impact on this binary. It was generated automatically. I tested the example app which works fine. Do you think I should remove it?

I am not sure. @albertodebortoli can you advise, please?

**Review by dchakarov — APPROVED** [review]

**Comment by albertodebortoli** [comment]
Agree with @dchakarov. The code for `_TweakAccessorGenerator` hasn't changed so the new binary shouldn't have been committed.
